import type { LucideIcon } from "lucide-react"
import {
  Award,
  BarChart3,
  BookOpen,
  Briefcase,
  Building2,
  CheckCircle2,
  Crosshair,
  Crown,
  Eye,
  Flame,
  Flag,
  Gamepad2,
  Gem,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  Layers,
  LayoutGrid,
  Lightbulb,
  LineChart,
  Mail,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Network,
  Newspaper,
  Phone,
  PieChart,
  Radio,
  Rocket,
  Send,
  Shield,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  TrendingUp,
  Trophy,
  Tv,
  Users,
  Users2,
  Video,
  Zap,
} from "lucide-react"

/** Whitelist имён иконок Lucide для блока «О нас» (CMS). */
export const ABOUT_CARD_ICON_MAP = {
  Target,
  Users,
  Crosshair,
  Heart,
  Zap,
  Shield,
  TrendingUp,
  Globe,
  Megaphone,
  Rocket,
  Gamepad2,
  Trophy,
  Star,
  Briefcase,
  Lightbulb,
  Sparkles,
  BarChart3,
  LineChart,
  PieChart,
  Users2,
  Eye,
  MessageCircle,
  Mail,
  Phone,
  Send,
  Award,
  Medal,
  Flag,
  Crown,
  Gem,
  Flame,
  Layers,
  LayoutGrid,
  Network,
  Radio,
  Tv,
  Video,
  Mic,
  Newspaper,
  BookOpen,
  GraduationCap,
  Building2,
  Handshake,
  ThumbsUp,
  CheckCircle2,
} as const satisfies Record<string, LucideIcon>

export type AboutCardIconName = keyof typeof ABOUT_CARD_ICON_MAP

export const ABOUT_CARD_ICON_NAMES = Object.keys(ABOUT_CARD_ICON_MAP) as AboutCardIconName[]

export function getAboutCardIcon(name: string): LucideIcon {
  const Icon = ABOUT_CARD_ICON_MAP[name as AboutCardIconName]
  return Icon ?? Target
}
